"""Tentative of using a C parser. Not included in testing."""
# -----------------------------------------------------------------
# https://github.com/eliben/pycparser/blob/master/examples/func_defs.py
# pycparser: func_defs.py
#
# Using pycparser for printing out all the functions defined in a
# C file.
#
# This is a simple example of traversing the AST generated by
# pycparser. Call it from the root directory of pycparser.
#
# Eli Bendersky [https://eli.thegreenplace.net/]
# License: BSD
# -----------------------------------------------------------------
from __future__ import print_function

from pycparser import c_ast, parse_file
from pycparserext.ext_c_parser import GnuCParser


# A simple visitor for FuncDef nodes that prints the names and
# locations of function definitions.
class FuncDefVisitor(c_ast.NodeVisitor):
    def visit_FuncDef(self, node):
        print(f"{node.decl.name} at {node.decl.coord}")


def _parse_file_to_ast(filename):
    parser = GnuCParser()
    ast = parse_file(
        filename,
        parser=parser,
        use_cpp=True,
        cpp_path="gcc",
        cpp_args=["-E", r"-Iobfuscator/data/fake_libc_include"],
    )
    return ast


def show_func_defs(filename):
    ast = _parse_file_to_ast(filename)
    visitor = FuncDefVisitor()
    visitor.visit(ast)


def show_ast(filename):
    ast = _parse_file_to_ast(filename)
    ast.show(showcoord=True)
